version: '3.4'

name: wheatherhunter

services:
  wheatherhunter.crawler:
    image: wheatherhunter-crawler
    build:
      context: .
      dockerfile: WeatherHunter.Crawler/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=Production